# Generated by Django 5.0.14 on 2026-06-23 02:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Crear'), ('update', 'Modificar'), ('delete', 'Eliminar')], max_length=20, verbose_name='Acción')),
                ('old_status', models.CharField(blank=True, choices=[('presente', 'Presente'), ('tardanza', 'Tardanza'), ('falta', 'Falta'), ('retiro_anticipado', 'Retiro Anticipado'), ('justificado', 'Justificado')], max_length=20, null=True, verbose_name='Estado Anterior')),
                ('new_status', models.CharField(choices=[('presente', 'Presente'), ('tardanza', 'Tardanza'), ('falta', 'Falta'), ('retiro_anticipado', 'Retiro Anticipado'), ('justificado', 'Justificado')], max_length=20, verbose_name='Estado Nuevo')),
                ('reason', models.TextField(verbose_name='Razón de la modificación')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
            ],
            options={
                'verbose_name': 'Auditoría de Asistencia',
                'verbose_name_plural': 'Auditorías de Asistencias',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('presente', 'Presente'), ('tardanza', 'Tardanza'), ('falta', 'Falta'), ('retiro_anticipado', 'Retiro Anticipado'), ('justificado', 'Justificado')], default='falta', max_length=20, verbose_name='Estado de Asistencia')),
                ('recorded_at', models.DateTimeField(blank=True, null=True, verbose_name='Registrado el')),
                ('recorded_by', models.CharField(choices=[('student_qr', 'Escaneo QR Alumno'), ('teacher_manual', 'Docente Manual'), ('admin_manual', 'Administrador Manual'), ('system_absent', 'Inasistencia Automática')], default='system_absent', max_length=20, verbose_name='Registrado por')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud Marcación')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud Marcación')),
                ('geo_valid', models.BooleanField(blank=True, null=True, verbose_name='Geolocalización Válida')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('start_time', models.TimeField(verbose_name='Hora de Inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de Fin')),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('active', 'Activa (QR Abierto)'), ('closed', 'Cerrada')], default='scheduled', max_length=20, verbose_name='Estado')),
                ('tolerance_minutes', models.IntegerField(default=15, verbose_name='Minutos de Tolerancia para Tardanza')),
            ],
            options={
                'verbose_name': 'Sesión de Clase',
                'verbose_name_plural': 'Sesiones de Clase',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Justification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Motivo/Sustento')),
                ('document_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL del Documento Adjunto')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resuelto el')),
            ],
            options={
                'verbose_name': 'Justificación de Inasistencia',
                'verbose_name_plural': 'Justificaciones de Inasistencia',
            },
        ),
        migrations.CreateModel(
            name='SessionQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=uuid.uuid4, max_length=100, unique=True, verbose_name='Código de Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('expires_at', models.DateTimeField(verbose_name='Expira el')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Código QR de Sesión',
                'verbose_name_plural': 'Códigos QR de Sesión',
            },
        ),
        migrations.CreateModel(
            name='AttendanceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje de Asistencia')),
                ('status', models.CharField(choices=[('green', 'Estable (Verde)'), ('yellow', 'Riesgo Moderado (Amarillo)'), ('red', 'Riesgo Alto (Rojo)')], max_length=20, verbose_name='Semáforo de Asistencia')),
                ('last_calculated', models.DateTimeField(auto_now=True, verbose_name='Último cálculo')),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='academics.academicperiod', verbose_name='Periodo Académico')),
            ],
            options={
                'verbose_name': 'Alerta de Asistencia',
                'verbose_name_plural': 'Alertas de Asistencia',
            },
        ),
    ]
