# Generated by Django 5.0.14 on 2026-06-23 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('attendance', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancealert',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='users.studentprofile', verbose_name='Alumno'),
        ),
        migrations.AddField(
            model_name='attendanceauditlog',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_audits', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que modificó'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='users.studentprofile', verbose_name='Alumno'),
        ),
        migrations.AddField(
            model_name='attendanceauditlog',
            name='attendance_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='attendance.attendancerecord', verbose_name='Registro de Asistencia'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academics.classroom', verbose_name='Aula'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academics.section', verbose_name='Sección'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.classsession', verbose_name='Sesión'),
        ),
        migrations.AddField(
            model_name='justification',
            name='attendance_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='justification', to='attendance.attendancerecord', verbose_name='Registro de Asistencia'),
        ),
        migrations.AddField(
            model_name='justification',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_justifications', to=settings.AUTH_USER_MODEL, verbose_name='Resuelto por'),
        ),
        migrations.AddField(
            model_name='sessionqrcode',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrs', to='attendance.classsession', verbose_name='Sesión'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancealert',
            unique_together={('student', 'academic_period')},
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('session', 'student')},
        ),
    ]
