# Generated by Django 5.0.14 on 2026-06-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Salida Registrada el'),
        ),
    ]
