# Generated by Django 5.0.14 on 2026-06-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.TextField(blank=True, null=True, verbose_name='Foto de Perfil (Base64)'),
        ),
    ]
